protected/controllers/ShopController.php
<?php

class ShopController extends Controller {

    public $layout = '//layouts/basic';

    public function filters() {
        return array(
            'accessControl',
//            'https',
        );
    }

    public function accessRules() {
        return array(
            array('allow',
                'users' => array('*'),
            ),
//            array('deny', // deny all users
//                'users' => array('*'),
//                'redirect' => array('admin/main/login'),
//            ),
        );
    }

    public function actionIndex($id) {
        $this->redirect('cart');
    }

    public function actionAddToCart($id, $amount = 1, $gift = false) {
        $deal = Deal::model()->findByPk($id);
        if ($deal) {
            if ($deal->hasUserReachedLimit()) {
                _user()->setFlash('notavailable', _t('shop', 'you have reached the maximum purchases allowed for this deal'));
            } elseif ($deal->available_coupons - $deal->coupons_bought < 1) {
                _user()->setFlash('notavailable', _t('shop', 'there are no more coupons available for this deal'));
            } else {
                isset(_app()->session['cart']) ? $cart = unserialize(_app()->session['cart']) : $cart = new Cart;
                $cart->add($deal, $amount);
                _app()->session['cart'] = serialize($cart);
            }
        }

        if ($gift) {
            _app()->session['gift'] = true;
        } else {
            if (isset(_app()->session['gift']))
                unset(_app()->session['gift']);
        }

        if (_user()->isGuest) {
            _user()->returnUrl = _url('shop/cart');
            $this->redirect(_url('user/login'));
        } else {
            $this->redirect('cart');
        }
    }

    public function actionCart() {
        $cart = isset(_app()->session['cart']) ? unserialize(_app()->session['cart']) : false;
        
        $gift = false;
        if (isset(_app()->session['gift-form'])) {
            $gift = unserialize(_app()->session['gift-form']);
            unset(_app()->session['gift-form']);
        } elseif (isset(_app()->session['gift'])) {
            $gift = new GiftForm;
        }

        $this->render('cart', array('cart' => $cart, 'gift' => $gift));
    }

    public function actionIncreaseAmount($id, $amount) {
        $deal = Deal::model()->findByPk($id);
        isset(_app()->session['cart']) ? $cart = unserialize(_app()->session['cart']) : $cart = new Cart;
        $cart->add($deal, $amount);
        _app()->session['cart'] = serialize($cart);

        Utils::jsonReturn(array(
            'status' => true,
            'price' => Utils::currency($amount * $deal->coupon_price),
            'total' => Utils::currency($cart->total),
            'recipients' => $this->recipientFields($amount),
        ));
    }

    public function actionPay() {
        if (isset($_POST['recipients']))
            $this->_storeCouponRecipients();

        if (isset($_POST['GiftForm']))
            $this->_storeGiftDetails();

        $factory = new CPaymentFactory;
        $p = $factory->build($_POST['type']);
        if (!$p->create(unserialize(_app()->session['cart'])))
            $this->redirect('cart');
    }

    public function actionVerify() {
        $factory = new CPaymentFactory;
        $p = $factory->build();
        if (!$p)
            $this->render('failure');
        $response = $p->verify($_REQUEST);
        if ($response) {
            $this->render('verify', array('response' => $response, 'cart' => unserialize(_app()->session['cart'])));
        } else {
            $this->render('failure');
        }
    }

    public function actionFailure() {
        $factory = new CPaymentFactory;
        $p = $factory->build();
        if (!$p)
            $this->render('failure');
        $response = $p->cancel($_REQUEST);
        $this->render('failure', array('response' => $response));
    }

    public function actionProcess() {
        $factory = new CPaymentFactory;
        $p = $factory->build();
        if (!$p)
            $this->render('failure');
        $response = $p->process($_REQUEST);
        if ($response) {
            $amount = $id = 0;
            if (isset(_app()->session['amount']) && isset(_app()->session['id'])) {
                $amount = _app()->session['amount'];
                $id = _app()->session['id'];
            }

            $this->render('success', array('response' => $response, 'amount' => $amount / 1.23, 'id' => $id));
        } else {
            $this->render('failure', array('response' => $response));
        }
    }

    public function actionCancel() {
        PPayment::cancel();
        $this->redirect('cart');
    }

    public function actionIpn() {
        CPaypalPayment::ipn($this);
    }

    public function actionCoupon() {
        $this->renderPartial('_coupon', array(
            'couponCode' => 'AS9757SD9759VDF',
            'deal' => Deal::model()->find(),
        ));
    }

    private function recipientFields($amount) {
        return $this->renderPartial('_recipientFields', array('amount' => $amount, 'name' => _profile()->details->fullname), true);
    }

    private function _storeCouponRecipients() {
        if (isset($_POST['sameRecipient']) && $_POST['recipients'][0] != '') {
            $recps = array($_POST['recipients'][0] => unserialize(_app()->session['cart'])->amount);
        } else {
            $recps = array();
            foreach ($_POST['recipients'] as $rec) {
                if ($rec != '') {
                    $recps[$rec] = isset($recps[$rec]) ? $recps[$rec] + 1 : 1;
                } else {
                    _user()->setFlash('error', _t('shop', 'recipient must not be empty'));
                    $this->redirect(_url('shop/cart'));
                }
            }
        }
        _app()->session['coupons'] = $recps;
    }

    private function _storeGiftDetails() {
        $gift = new GiftForm;
        $gift->attributes = $_POST['GiftForm'];
        
        if ($gift->validate()) {
            _app()->session['coupons'] = array($_POST['GiftForm']['fullname'] => 1);
            _app()->session['gift'] = $_POST['GiftForm'];
            return true;
        } else {
            _app()->session['gift-form'] = serialize($gift);
            $this->redirect(_url('shop/cart'));
        }
    }

}

protected/views/shop/_coupon.php
<style type="text/css">
    body,td,th {
        color: #3C3C3C;
        font-family: Arial, Helvetica, sans-serif;
    }
    a:link {
        color: #FFFFFF;
        text-decoration: none;
    }
    a:visited {
        color: #FFFFFF;
        text-decoration: none;
    }
    a:hover {
        text-decoration: none;
    }
    a:active {
        text-decoration: none;
    }
</style>
<table width="601" height="705" border="0" align="center" >
    <tr>
        <td width="595" height="701" valign="top" bgcolor="#3c3c3c"><table width="601" border="0">
                <tr>
                    <td width="590" bgcolor="#3c3c3c"><table width="601" border="0">
                            <tr>
                                <td width="343"><div class="span-2 append-1 logo"><?php echo CHtml::link(CHtml::image(_app()->createAbsoluteUrl('images/logo.png')), _app()->createAbsoluteUrl('site/index')); ?></div></td>
                                <td width="248" valign="top" align="right" style="color: white;"><?php echo Utils::date(date('Y-m-d'), array('time' => false, 'year' => true, 'monthAbbreviated' => false, 'dayAbbreviated' => false)); ?></td>
                            </tr>
                        </table></td>
                </tr>
            </table>
            <table width="595" border="0" align="center" bgcolor="#FFFFFF">
                <tr>
                    <td width="595" height="623"><table width="591" border="0">
                            <tr>
                                <td width="203"><table width="200" border="0">
                                        <tr>
                                            <td><strong><?php echo _t('coupon', 'coupon number'); ?></strong></td>
                                        </tr>
                                        <tr>
                                            <td height="43"><strong><?php echo $coupon->coupon_code; ?></strong></td>
                                        </tr>
                                    </table></td>
                                <td width="378"><table width="310" border="0" align="right">
                                        <tr>
                                            <td width="124" align="right"><strong><?php echo _t('coupon', 'full name'); ?>:</strong></td>
                                            <td width="176" align="right"><?php echo $coupon->name; ?></td>
                                        </tr>
                                        <tr>
                                            <td align="right"><strong><?php echo _t('coupon', 'expiration date'); ?>:</strong></td>
                                            <td align="right"><?php echo $coupon->transaction->deal->coupon_valid_to; ?></td>
                                        </tr>
                                    </table></td>
                            </tr>
                        </table>
                        <p><br>
                            <strong><?php echo _t('coupon', 'your deal'); ?></strong><br>
                            <br>
                            <?php echo $coupon->transaction->deal->details->coupon_instructions; ?><br>
                            <br>
                            <br>
                            <br>
                            <strong><?php echo _t('coupon', 'location directions'); ?></strong></p>
                        <table width="525" border="0">
                            <tr>
                                <td width="294" height="247" bgcolor="#999999"><img src="http://maps.googleapis.com/maps/api/staticmap?center=
                                 <?php echo urlencode($coupon->transaction->deal->company->coordinates); ?>&markers=size:mid|
                                 <?php echo urlencode($coupon->transaction->deal->company->coordinates); ?>&zoom=14&size=300x250&maptype=roadmap&sensor=false"></td>
                                <td width="215" valign="top"><?php echo $coupon->transaction->deal->company->name; ?><br>
                                    <?php echo $coupon->transaction->deal->company->address; ?><br>
                                    <?php echo $coupon->transaction->deal->company->phone; ?><br>
                                    <?php echo $coupon->transaction->deal->company->email; ?></td>
                            </tr>
                        </table>
                        <p><?php echo _t('coupon', 'thank you for choosing dealspot'); ?><br>
                        </p></td>
                </tr>
            </table>
            <table width="600" border="0">
                <tr>
                    <td width="169"><?php echo CHtml::link(CHtml::image(_app()->createAbsoluteUrl('images/logo.png'), '', array('width' => 169, 'height' => 34)), _app()->createAbsoluteUrl('site/index')); ?></td>
                    <td width="415">&nbsp;</td>
                </tr>
            </table></td>
    </tr>
</table>

protected/views/shop/_gift.php
<?php
Utils::registerCssFile('mobiscroll-2.3.custom.min');
Utils::registerJsFile('mobiscroll-2.3.custom.min');
?>
<?php
$form = $this->beginWidget('CActiveForm', array(
                'id' => 'cart-form',
                'action' => 'pay',
                    ));
?>
<div class="gift">
    <?php echo $form->errorSummary($gift); ?>
    <div class="left">
        <?php echo $form->label($gift, 'fullname'); ?>
        <?php echo $form->textField($gift, 'fullname'); ?>
        <?php echo $form->label($gift, 'email'); ?>
        <?php echo $form->textField($gift, 'email'); ?>
        <div class="clear"></div>
        <div>
            <?php echo $form->label($gift, 'paper'); ?>
            <br/>
            <?php $i = 1; ?>
            <?php foreach ($papers as $paper) : ?>
                <?php echo CHtml::image($paper->url, '', array('id' => $paper->id, 'class' => $i >= count($papers) ? 'paper last' : 'paper')); ?>
                <?php ++$i; ?>
            <?php endforeach; ?>
            <?php echo $form->hiddenField($gift, 'paper'); ?>
        </div>
    </div>
    <div class="right">
        <?php echo $form->label($gift, 'unwrap_time'); ?>
        <?php echo $form->textField($gift, 'unwrap_time'); ?>
        <?php echo $form->label($gift, 'personal_message'); ?>
        <?php echo $form->textArea($gift, 'personal_message', array('style' => 'width: 220px; height: 100px;')); ?>
        
        <?php echo _app()->wagclient->getTooltip(); ?>
    </div>
    <div class="clear"></div>
</div>
<?php echo CHtml::hiddenField('type'); ?>
<?php $this->endWidget(); ?>
<script>
    $(function(){
        $(".paper").click(function(){
            $(this).siblings().removeClass('selected');
            $(this).addClass('selected');
            $('#GiftForm_paper').val($(this).attr("id"));
        });
        
        var now = new Date();
        
        (function ($) {
            $.mobiscroll.i18n.el = $.extend($.mobiscroll.i18n.el, {
                setText: 'OK',
                cancelText: 'Αναίρεση'
            });
        })(jQuery);
        
        (function ($) {
            $.mobiscroll.i18n.el = $.extend($.mobiscroll.i18n.el, {
                dateFormat: 'dd-mm-yy',
                dateOrder: 'ddmmyy',
                dayNames: ['Κυριακή', 'Δευτέρα', 'Τρίτη', 'Τετάρτη', 'Πέμπτη', 'Παρασκευή', 'Σάββατο'],
                dayNamesShort: ['Κυ', 'Δε', 'Τρ', 'Τε', 'Πε', 'Πα', 'Σα'],
                dayText: 'Ημέρα',
                hourText: 'Ώρα',
                minuteText: 'Λεπτό',
                monthNames: ['ιανουάριος', 'Φεβρουάριος', 'Μάρτιος', 'Απρίλιος', 'Μάιος', 'Ιούνιος', 'Ιούλιος', 'Αύγουστος', 'Σεπτέμβριος', 'Οκτώβριος', 'Νοέμβριος', 'Δεκέμβριος'],
                monthNamesShort: ['Ιαν', 'Φεβ', 'Μαρ', 'Απρ', 'Μαι', 'Ιον', 'Ιολ', 'Αυγ', 'Σεπ', 'Οκτ', 'Νοε', 'Δεκ'],
                monthText: 'Μήνας',
                secText: 'Δευτ/λεπτο',
                timeFormat: 'HH:ii',
                timeWheels: 'HHii',
                yearText: 'Έτος'
            });
        })(jQuery);

        $('#GiftForm_unwrap_time').scroller({
            preset: 'datetime',
            minDate: new Date(now.getFullYear(), now.getMonth(), now.getDate(), now.getHours(), now.getMinutes() + 5),
            display: 'bubble',
            animate: 'fade',
            mode: 'clickpick',
            lang: '<?php echo _app()->language; ?>'
        });
    })
</script>

protected/views/shop/_recipientFields.php
<?php echo CHtml::form('pay', 'post', array('id' => 'cart-form')); ?>
    <?php echo _user()->hasFlash('error') ? CHtml::tag('span', array('class' => 'error'), _user()->getFlash('error')) : ''; ?>
    <div class="recipient1">
        <?php echo CHtml::label(_t('shop', 'recipient {number}: ', array('{number}' => 1)), 'recipients[]'); ?>
        <?php echo CHtml::textField('recipients[]', $name); ?>
    </div>
    <?php for ($i = 2; $i <= $amount; ++$i) : ?>
        <div class="recipient<?php echo $i; ?>">
            <?php echo CHtml::label(_t('shop', 'recipient {number}: ', array('{number}' => $i)), 'recipients[]'); ?>
            <?php echo CHtml::textField('recipients[]'); ?>
        </div>
    <?php endfor; ?>
    <?php if ($amount > 1) : ?>
        <div>
            <?php echo CHtml::checkBox('sameRecipient'); ?>
            <?php echo CHtml::label(_t('shop', 'recipient 1 for all coupons'), 'sameRecipient'); ?>
        </div>
    <?php endif; ?>
    <?php echo CHtml::hiddenField('type'); ?>
<?php echo CHtml::endForm(); ?>

protected/views/shop/cart.php
<div class="cart">
    <div class="progress-bar">
        <?php echo CHtml::image(Utils::imageUrl('bar1.png')); ?>
    </div>
    <?php if (_user()->hasFlash('notavailable')) : ?>
        <div class="errorSummary"><?php echo _user()->getFlash('notavailable'); ?></div>
    <?php elseif ($cart) : ?>
        <?php if (_user()->hasFlash('nopoints')) : ?>
            <div class="errorSummary"><?php echo _user()->getFlash('nopoints'); ?></div>
        <?php endif; ?>
        <div class="cart-header cart-item">
            <div class="name"><?php echo _t('shop', 'item'); ?></div>
            <div class="amount text-right"><?php echo _t('shop', 'amount'); ?></div>
            <div class="item-price"><?php echo _t('shop', 'item price'); ?></div>
            <div class="price"><?php echo _t('shop', 'price'); ?></div>
        </div>
        <div class="clearfix"></div>
        <div class="cart-items">
            <div class="cart-item">
                <div class="name"><?php echo $cart->deal->name; ?>
                    <?php if (isset($cart->deal->details)) : ?>
                        -
                        <span><?php echo $cart->deal->details->subtitle; ?></span>
                    <?php endif; ?>
                </div>
                <div class="amount" style="text-align: right">
                    <?php if ($gift) : ?>
                        <?php
                        echo $cart->amount;
                        ?>
                    <?php else : ?>
                        <?php
                        echo CHtml::dropDownList('amount', $cart->amount, $cart->deal->getCouponsAvailableArray(), array('id' => 'amount', 'class' => 'right amount-dropdown'));
                        ?>
                    <?php endif; ?>
                </div>
                <div class="item-price"><?php echo Utils::currency($cart->deal->coupon_price); ?></div>
                <div class="price"><?php echo Utils::currency($cart->total); ?></div>
                <?php echo CHtml::hiddenField('id', $cart->deal->id, array('id' => 'itemID')); ?>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="recipients-block">
            <?php if ($gift) : ?>
                <?php $this->renderPartial('_gift', array('papers' => _app()->wagclient->getPapers(), 'gift' => $gift)); ?>
            <?php else : ?>
                <?php $this->renderPartial('_recipientFields', array('amount' => $cart->amount, 'name' => _profile()->details->fullname)); ?>
            <?php endif; ?>
        </div>
        <div class="payment-methods">
            <ul>
                <li>
                    <?php echo CHtml::image(Utils::imageUrl('number-1.png')); ?>
                    <span><?php echo _t('shop', 'pay by bank'); ?></span>
                    <div class="payment-details">
                        <div class="payment-description">
                            <?php echo _t('shop', 'description for bank payment'); ?>
                        </div>
                        <div class="payment-image">
                            <?php echo CHtml::image(Utils::imageUrl('bank.png')); ?>
                        </div>
                        <div class="payment-button">
                            <?php echo CHtml::link(Chtml::image(Utils::imageUrl('button.jpg')), '#', array('class' => 'payment-button', 'type' => PaymentMethod::BANK)); ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                </li>
                <li>
                    <?php echo CHtml::image(Utils::imageUrl('number-2.png')); ?>
                    <span><?php echo _t('shop', 'pay by hellaspay'); ?></span>
                    <div class="payment-details">
                        <div class="payment-description">
                            <?php echo _t('shop', 'description for hellaspay payment'); ?>
                        </div>
                        <div class="payment-image">
                            <?php echo CHtml::image(Utils::imageUrl('hellaspay.png')); ?>
                        </div>
                        <div class="payment-button">
                            <?php echo CHtml::link(Chtml::image(Utils::imageUrl('button.jpg')), '#', array('class' => 'payment-button', 'type' => PaymentMethod::HELLASPAY)); ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                </li>
                <li>
                    <?php echo CHtml::image(Utils::imageUrl('number-3.png')); ?>
                    <span><?php echo _t('shop', 'pay by paypal'); ?></span>
                    <div class="payment-details">
                        <div class="payment-description">
                            <?php echo _t('shop', 'description for paypal payment'); ?>
                        </div>
                        <div class="payment-image">
                            <?php echo CHtml::image(Utils::imageUrl('paypal.png')); ?>
                        </div>
                        <div class="payment-button">
                            <?php echo CHtml::link(Chtml::image(Utils::imageUrl('button.jpg')), '#', array('class' => 'payment-button', 'type' => PaymentMethod::PAYPAL)); ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                </li>
                <li>
                    <?php echo CHtml::image(Utils::imageUrl('number-4.png')); ?>
                    <span><?php echo _t('shop', 'pay by points'); ?></span>
                    <div class="payment-details">
                        <div class="payment-description">
                            <?php echo _t('shop', 'description for points payment'); ?>
                        </div>
                        <div class="payment-image">
                            <?php echo CHtml::image(Utils::imageUrl('points.png')); ?>
                        </div>
                        <div class="payment-button">
                            <?php echo CHtml::link(Chtml::image(Utils::imageUrl('button.jpg')), '#', array('class' => 'payment-button', 'type' => PaymentMethod::POINTS)); ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                </li>
            </ul>
        </div>
    <?php else : ?>
        <?php echo _t('shop', 'no items in cart'); ?>
    <?php endif; ?>
    <div><?php echo CHtml::link(_t('shop', 'cancel'), _url('site/index')); ?></div>
    <div class="clearfix"></div>
</div>
<script>
    $(document).ready(function() {
        $("#amount").live('change', function() {
            $.ajax({
                url: '<?php echo _url('shop/increaseAmount'); ?>',
                data: {id: $(this).parent().parent().children("#itemID").val(), amount: $(this).val()},
                type: 'get',
                success: $.proxy(function(data) {
                    if (data.status) {
                        $(this).parent().parent().children(".price").fadeOut(200, function() {
                            $(this).html(data.price).fadeIn(200);
                        });
                        $(".recipients-block").html(data.recipients);
                    }
                }, this)
            });
        });

        $(".payment-button").click(function(){
            $("#type").val($(this).attr("type"));
            $("#cart-form").submit();
            return false;
        })
    })
</script>

protected/views/shop/failure.php
<?php echo _t('shop', 'your payment has failed'); ?>

protected/views/shop/index.php
hi

protected/views/shop/pending.php
<?php echo _t('shop', 'your payment is pending'); ?>

protected/views/shop/success.php
<div class="cart">
    <div class="progress-bar">
        <?php echo CHtml::image(Utils::imageUrl('bar3.png')); ?>
    </div>
    <h3>
        <?php echo _t('shop', 'your order is succesfully completed.'); ?>
        <?php echo CHtml::image(Utils::imageUrl('green-check.png'), '', array('style' => 'vertical-align:middle;')); ?>
    </h3>
    <div class="grey-box">
        <?php echo _user()->hasFlash('gift-error') ? '<div class="error">' . _user()->getFlash('gift-error') . '</div>' : ''; ?>
        <?php echo $response; ?>
        <div style="text-align: center;"><?php echo _t('shop', 'for any questions you can contact the dealspot team to guide you'); ?></div>
        <div style="text-align: center;"><?php echo _t('shop', 'thank you for choosing dealspot'); ?></div>
        <div style="text-align: right;">
            <?php echo CHtml::link(_t('shop', 'go back'), _url('site/index')); ?>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://gr.linkwi.se/delivery/lwc/lwc.js"></script>
<script type="text/javascript">
    Linkwise.load_action("258", "<?php echo $id; ?>", "1::<?php echo $amount; ?>", "", "pending");
</script>
<noscript>
<img src="https://gr.linkwi.se/delivery/acl.php?cam_id=258&amp;trans_id=<?php echo $id; ?>&amp;sale_amount=1::<?php echo $amount; ?>&amp;adv_subid=&amp;status=pending" style="width:0px;height:0px;"/>
</noscript>

protected/views/shop/verify.php
<div class="cart">
    <div class="progress-bar">
        <?php echo CHtml::image(Utils::imageUrl('bar2.png')); ?>
    </div>
    <?php if ($cart) : ?>
        <div class="cart-content-box-container long">
            <h3><?php echo _t('shop', 'your deal'); ?></h3>
            <div class="cart-content-box">
                <?php echo $cart->deal->details->coupon_instructions; ?>
            </div>
        </div>
        <div class="cart-content-box-container short">
            <h3><?php echo _t('shop', 'payment method'); ?></h3>
            <div class="cart-content-box" style="text-align: center;">
                <?php echo CHtml::image($response['image']); ?>
            </div>
        </div>
        <div class="cart-content-box-container short-last">
            <h3><?php echo _t('shop', 'deal cost'); ?></h3>
            <div class="cart-content-box">
                <div><?php echo _t('shop', 'amount'); ?>:<span class="text-right right"><?php echo $cart->amount; ?></span></div>
                <div><?php echo _t('shop', 'price per unit'); ?>:
                    <span class="text-right right"><?php echo Utils::currency($cart->deal->coupon_price); ?></span></div>
                <hr/>
                <div><?php echo _t('shop', 'total'); ?>:<span class="text-right right" style="font-size: 2em; margin-top: -13px;">
                        <?php echo Utils::currency($cart->total); ?></span></div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="cart-content-box-container full last">
            <div class="cart-content-box">
                <div class="span-5"><?php echo $response['text']; ?></div>
                <div class="span-1 last">
                    <form action="<?php echo _url('shop/process'); ?>" method="post">
                        <?php if (isset($response['TOKEN'])) : ?>
                            <input type="hidden" name="token" value="<?php echo $response['TOKEN']; ?>">
                        <?php endif; ?>
                        <?php if (isset($response['PAYERID'])) : ?>
                            <input type="hidden" name="payerID" value="<?php echo $response['PAYERID']; ?>">
                        <?php endif; ?>
                        <input type="hidden" name="amount" value="<?php echo $cart->total; ?>">
                        <input type="image" src="<?php echo Utils::imageUrl('confirm-button.png'); ?>" value="<?php echo _t('shop', 'click to complete payment'); ?>">
                    </form>
                </div>
            </div>
        </div>
        <div><?php echo CHtml::link(_t('shop', 'cancel'), _url('site/index')); ?></div>
        <div class="clearfix"></div>
    <?php else : ?>
        <?php echo _t('shop', 'no items in cart'); ?>
    <?php endif; ?>
</div>