protected/modules/admin/controllers/TransactionsController.php
<?php
class TransactionsController extends AdminController {

    /**
     * Declares class-based actions.
     */
    public function filters() {
        return array(
            'accessControl',
        );
    }

    public function accessRules() {
        return array(
            array('allow',
                'expression' => 'User::hasRole(Role::ADMIN | Role::DEV)',
            ),
            array('deny', // deny all users
                'users' => array('*'),
                'redirect' => array('admin/main/login'),
            ),
        );
    }

    public function actionIndex() {
        $trans = new Transaction('search');
        if (isset($_GET['Transaction']))
            $trans->attributes = $_GET['Transaction'];

        $trans->status = Transaction::COMPLETED;

        $this->render('index', array('trans' => $trans));
    }

    public function actionPending() {
        $trans = new Transaction('search');

        if (isset($_GET['Transaction']))
            $trans->attributes = $_GET['Transaction'];

        $trans->status = Transaction::VERIFIED;

        $this->render('pending', array('trans' => $trans));
    }

    public function actionProcess($id) {
        $trans = Transaction::model()->findByPk($id);
        if ($trans)
            $trans->complete();

        $this->redirect(_aurl('transactions/pending'));
    }

}

protected/modules/admin/views/transactions/index.php
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $trans->search(),
    'filter' => $trans,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),
    'template' => '{items}{pager}',
    'columns' => array(
        array(
            'name' => 'user_username',
            'value' => '$data->user->username',
        ),
        array(
            'name' => 'deal.name',
        ),
        array(
            'name' => 'amount',
            'value' => 'Utils::currency($data->amount)',
            'filter' => false,
        ),
        array(
            'name' => 'payment_method',
            'value' => 'PaymentMethod::text($data->payment_method)',
            'filter' => PaymentMethod::getArray(),
        ),
        array(
            'name' => 'transaction_date',
            'value' => 'Utils::date($data->transaction_date)',
            'filter' => false,
        ),
        array(
            'header' => _t('admin', 'coupons'),
            'value' => 'count($data->coupons)',
        ),
    ),
));

protected/modules/admin/views/transactions/pending.php
<?php
$this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $trans->search(),
    'filter' => $trans,
    'pager' => array('class' => 'CLinkPager', 'header' => ''),
    'template' => '{items}{pager}',
    'columns' => array(
        array(
            'name' => 'user_username',
            'value' => '$data->user->username',
        ),
        array(
            'name' => 'deal.name',
        ),
        array(
            'name' => 'amount',
            'value' => 'Utils::currency($data->amount)',
            'filter' => false,
        ),
        array(
            'name' => 'payment_method',
            'value' => 'PaymentMethod::text($data->payment_method)',
            'filter' => PaymentMethod::getArray(),
        ),
        array(
            'name' => 'transaction_date',
            'value' => 'Utils::date($data->transaction_date)',
            'filter' => false,
        ),
        array(
            'header' => _t('admin', 'coupons'),
            'value' => 'count($data->coupons)',
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{process}',
            'buttons' => array(
                'process' => array(
                    'label' => _t('admin', 'process transaction'),
                    'url' => '_aurl("transactions/process", array("id" => $data->id))',
                    'imageUrl' => Utils::adminImageUrl('process.png'),
                ),
            ),
        ),
    ),
));