protected/controllers/UserController.php
<?php
class UserController extends Controller {
    public $layout = '//layouts/basic';

    public function filters() {
        return array(
            'accessControl',
//            'https',
        );
    }

    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index', 'login', 'register', 'activate', 'forgotPassword', 'resetCode', 'resetPassword', 'changePassword', 'submitPassword', 'test'),
                'users' => array('*'),
            ),
            array('allow',
                'expression' => 'Utils::isLoggedIn()',
            ),
            array('deny', // deny all users
                'users' => array('*'),
                'redirect' => array('site/index'),
            ),
        );
    }

    public function actionIndex() {
        $this->render('index');
    }

    public function actionLogin() {
        if (!_user()->isGuest)
            $this->redirect(_url('site/index'));
        $model = new LoginForm;
        $user = new User;
        $userDetails = new UserDetails;

        if (isset($_GET['invitation_code'])) {
            _app()->session['invite_code'] = $_GET['invitation_code'];
            $invitation = UserInvite::model()->find('code = :code', array(':code' => $_GET['invitation_code']));
            if ($invitation)
                $user->email = $user->email2 = $invitation->invited_email;
        }

        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            if ($model->validate() && $model->login())
                $this->redirect(_user()->returnUrl);
        }
        $this->render('login', array('model' => $model, 'user' => $user, 'userDetails' => $userDetails));
    }

    public function actionRegister() {
        if (isset($_POST['User']) && isset($_POST['UserDetails'])) {
            $user = new User;
            $userDetails = new UserDetails;
            $user->attributes = $_POST['User'];
            $userDetails->attributes = $_POST['UserDetails'];
            $user->role = Role::USER;

            if ($user->save()) {
                $userDetails->user_id = $user->id;
                if ($userDetails->save()) {
                    if ($user->source == UserSource::FACEBOOK) {
                        $login = new LoginForm;
                        $login->username = $user->username;
                        $login->password = $_POST['User']['password'];
                        if ($login->login())
                            $this->redirect(_user()->returnUrl);
                    } else {
                        $user->createActivationCode();
                        $this->render('awaiting_activation');
                        Yii::app()->end();
                    }
                }
            } else {
                $model = new LoginForm;
                $this->render('login', array('model' => $model, 'user' => $user, 'userDetails' => $userDetails));
            }
        }
    }

    public function actionActivate($code) {
        $userAct = UserActivation::model()->verifyCode($code);
        if ($userAct) {
            $userAct->delete();

            $this->render('activation_success');
            _app()->end();
//            $login = new LoginForm;
//            $login->username = $user->username;
//            if ($login->login())
//                $this->redirect(_user()->returnUrl);
        }
        $this->render('activation_failed');
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(_url('site/index'));
    }

    public function actionInvite() {
        if (Utils::isAjax() && isset($_POST['invitee'])) {
            $response = array();
            if (_profile())
                $response = _profile()->sendInviteEmail($_POST['invitee']);
            Utils::jsonReturn($response);
        }
        return;
    }

    public function actionProfile($view = 'details', $companyDetails = false) {

        if (isset($_POST['pass']))
            _profile()->changePassword($_POST['pass']['new'], $_POST['pass']['repeat']);

        _profile()->refresh();
        Utils::registerJsFile('jquery.jeditable.mini', CClientScript::POS_BEGIN);
        Utils::registerJsFile('jeditable.checkbox', CClientScript::POS_BEGIN);

        $selected = array(
            'deals' => '',
            'invites' => '',
            'points' => '',
            'details' => '',
            'company' => '',
        );
        switch ($view) {
            case 'deals':
                $selected['deals'] = 'show';
                break;
            case 'invites':
                $selected['invites'] = 'show';
                break;
            case 'points':
                $selected['points'] = 'show';
                break;
            case 'company':
                $selected['company'] = 'show';
                break;
            case 'details':
            default:
                $selected['details'] = 'show';
                break;
        }

        $details = $this->renderPartial('_details', null, true);
        $deals = $this->renderPartial('_deals', null, true);
        $invites = $this->renderPartial('_invites', null, true);
        $points = $this->renderPartial('_points', null, true);
        if (User::hasRole(Role::CLIENT))
            $company = $this->renderPartial('_company', array('id' => $companyDetails), true);
        else
            $company = false;

        $this->render('profile', array('selected' => $selected, 'details' => $details, 'deals' => $deals, 'invites' => $invites, 'points' => $points, 'company' => $company));
    }

    public function actionDeals() {
        $this->renderPartial('_deals');
    }

    public function actionDetails() {
        $this->renderPartial('_details');
    }

    public function actionInvites() {
        $this->renderPartial('_invites');
    }

    public function actionPoints() {
        $this->renderPartial('_points');
    }

    public function actionCompany() {
        $this->renderPartial('_company', array('id' => false));
    }

    public function actionUpdateProfile() {
        if (!Utils::isAjax())
            return;

        if (!isset($_POST['id']))
            return;

        $attribute = $_POST['id'];

        if (isset(_profile()->$attribute)) {
            $oldValue = _profile()->$attribute;

            if (_profile()->$attribute != $_POST['value']) {

                // Update only if value is different
                _profile()->$attribute = $_POST['value'];
                if (!_profile()->save(false, array($attribute))) {
                    var_dump(_profile()->getErrors());
                }

                // After refresh, the old values will return if the udpate failed.
                _profile()->refresh();
            }

            switch ($attribute) {
                default:
                    echo _profile()->$attribute;
                    break;
            }
        } else {
            $oldValue = _profile()->details->$attribute;

            if (_profile()->details->$attribute != $_POST['value']) {

                // Update only if value is different
                _profile()->details->$attribute = $_POST['value'];

                if ($attribute == 'newsletter') {
                    _profile()->details->$attribute = $_POST['value'] == _t('profile', 'yes') ? 1 : 0;
                }

                if (!_profile()->details->save(true, array($attribute))) {
                    var_dump(_profile()->details->getErrors());
                }

                // After refresh, the old values will return if the udpate failed.
                _profile()->details->refresh();
            }

            switch ($attribute) {
                case 'birthdate':
                    echo _profile()->details->birthdate;
                    break;
                case 'gender':
                    echo Gender::toText(_profile()->details->gender);
                    break;
                case 'newsletter':
                    echo _profile()->details->newsletter ? _t('profile', 'yes') : _t('profile', 'no');
                    break;
                default:
                    echo _profile()->details->$attribute;
                    break;
            }
        }

        _app()->end();
    }

    public function actionDealDetails($id) {
        $deal = Deal::model()->findByPk($id);

        $this->renderPartial('_dealDetails', array('coupons' => $deal->allCoupons));
    }

    public function actionCoupon($id) {
        $coupon = Coupon::model()->findByPk($id);
        if ($coupon && _profile()) {
            $coupon->is_active = !$coupon->is_active;
            $coupon->date_activated = date(DATE_ISO8601);
            $coupon->user_id = _profile()->id;
            $coupon->save();
        }

        $this->redirect(_url('user/profile', array('view' => 'company', 'companyDetails' => $coupon->transaction->deal->id)));
    }

    public function actionPrintCoupon($id) {
        $coupon = Coupon::model()->findByPk($id);
        if (!$coupon || ($coupon && _profile()->id != $coupon->transaction->user->id))
            $this->redirect(_url('site/index'));

        $this->layout = 'print';
        $this->render('coupon', array('coupon' => $coupon));
    }

    public function actionForgotPassword() {
        $this->render('forgotPasswordForm');
    }

    public function actionResetCode() {
        if (isset($_POST['email'])) {
            $user = User::model()->find('email = :email', array(':email' => $_POST['email']));
            if ($user && $user->createResetCode()) {
                $this->render('resetCode');
                _app()->end();
            }
        }

protected/views/user/_company.php
<h2><?php echo _t('profile', 'my company'); ?></h2>
<div class="my-company">
    <?php if ($id) :
        $deal = Deal::model()->findByPk($id);
        $this->renderPartial('_dealDetails', array('coupons' => $deal->allCoupons));
    else : ?>
    <table class="custom-table">
        <thead>
            <tr>
                <th><?php echo _t('profile', 'deal'); ?></th>
                <th><?php echo _t('profile', 'status'); ?></th>
                <th><?php echo _t('profile', 'start date'); ?></th>
                <th><?php echo _t('profile', 'end date'); ?></th>
                <th><?php echo _t('profile', 'sales'); ?></th>
                <th><?php echo _t('profile', 'amount'); ?></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach (_profile()->company->deals as $deal) : ?>
                <tr style="background-color:<?php echo $deal->isActive() ? '#d3ffd1' : 'pink'; ?>">
                    <td><?php echo $deal->name; ?></td>
                    <td><?php echo $deal->isActive() ? _t('profile', 'active') : _t('profile', 'inactive'); ?></td>
                    <td><?php echo Utils::date($deal->valid_from); ?></td>
                    <td><?php echo Utils::date($deal->valid_to); ?></td>
                    <td><span class="blue"><?php echo count($deal->transactions); ?></span></td>
                    <td><span class="blue"><?php echo Utils::currency(Transaction::getSalesByDeal($deal->id)); ?></span></td>
                    <td><?php echo CHtml::linkButton(CHtml::image(Utils::imageUrl('details.png')), array('class' => 'details', 'id' => $deal->id)); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php endif; ?>
</div>
<script>
    $(function(){
        $(".details").click(function(){
            var deal = $(this).attr("id");
            $.ajax({
                url: '<?php echo _url('user/dealDetails'); ?>?id=' + deal,
                type: 'get',
                success: function(data) {
                    $(".my-company").html(data);
                }
            })
            return false;
        })
    })
</script>

protected/views/user/_dealDetails.php
<table class="custom-table">
    <thead>
        <tr>
            <th><?php echo _t('profile', 'coupon code'); ?></th>
            <th><?php echo _t('profile', 'name'); ?></th>
            <th><?php echo _t('profile', 'email'); ?></th>
            <th><?php echo _t('profile', 'date bought'); ?></th>
            <th><?php echo _t('profile', 'date used'); ?></th>
            <th><?php echo _t('profile', 'status'); ?></th>
            <th><?php echo _t('profile', 'manager'); ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($coupons as $coupon) : ?>
            <tr style="background-color:<?php echo $coupon->is_active ? '#d3ffd1' : 'pink'; ?>">
                <td><?php echo $coupon->coupon_code; ?></td>
                <td><?php echo $coupon->transaction->user->details->fullname; ?></td>
                <td><?php echo $coupon->transaction->user->email; ?></td>
                <td><?php echo Utils::date($coupon->transaction->transaction_date); ?></td>
                <td><?php echo $coupon->date_activated ? Utils::date($coupon->date_activated) : '-'; ?></td>
                <td><?php echo $coupon->is_active ? _t('profile', 'available') : _t('profile', 'used'); ?>
                </td>
                <td><?php echo isset($coupon->user) ? $coupon->user->username : '-'; ?></td>
                <td>
                    <?php
                    if (!isset($coupon->user)) :
                        echo CHtml::link(CHtml::image(Utils::imageUrl('gears.png')), _url('user/coupon', array('id' => $coupon->id)));
                    else :
                        echo CHtml::link(CHtml::image(Utils::imageUrl('gears.png')), _url('user/coupon', array('id' => $coupon->id)));
                    endif;
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

protected/views/user/_deals.php
<table class="custom-table">
    <thead>
        <tr>
            <th><?php echo _t('profile', 'deals'); ?></th>
            <th><?php echo _t('profile', 'date of sale'); ?></th>
            <th><?php echo _t('profile', 'expiration'); ?></th>
            <th><?php echo _t('profile', 'payment method'); ?></th>
            <th><?php echo _t('profile', 'amount paid'); ?></th>
            <th><?php echo _t('profile', 'code'); ?></th>
            <th><?php echo _t('profile', 'active'); ?></th>
            <th><?php echo _t('profile', 'print'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (_profile()->transactions as $transaction) : ?>
            <?php foreach ($transaction->coupons as $coupon) : ?>
                <tr style="background-color:<?php echo $coupon->is_active ? '#d3ffd1' : 'pink'; ?>">
                    <td><?php echo $transaction->deal->name; ?></td>
                    <td><?php echo Utils::date($transaction->transaction_date); ?></td>
                    <td><?php echo Utils::date($transaction->deal->coupon_valid_to); ?></td>
                    <td><?php echo PaymentMethod::text($transaction->payment_method); ?></td>
                    <td><?php echo Utils::currency($transaction->deal->coupon_price); ?></td>
                    <td><?php echo $coupon->coupon_code; ?></td>
                    <td><?php echo $coupon->is_active ? _t('profile', 'yes') : _t('profile','no'); ?></td>
                    <td><?php echo CHtml::link(CHtml::image(Utils::imageUrl('print.png')),
                            $coupon->is_active ? _url('user/printCoupon', array('id' => $coupon->id)) : '#'); ?></td>
                </tr>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </tbody>
</table>

protected/views/user/_details.php
<div class="details">
    <h2 style="color: #484743;"><?php echo _t('profile', 'account') . ':&nbsp;' . _profile()->username; ?></h2>
    <label><?php echo _t('profile', 'full name'); ?></label>
    <?php echo CHtml::tag('div', array(
        'id' => 'fullname',
        'class' => 'editable',
            ), _profile()->details->fullname
    ); ?>
    <label><?php echo _t('profile', 'email'); ?></label>
    <?php echo CHtml::tag('div', array(
        'id' => 'email',
        'class' => 'editable',
            ), _profile()->email
    ); ?>
    <label><?php echo _t('profile', 'gender'); ?></label>
    <?php echo CHtml::tag('div', array(
        'id' => 'gender',
        'class' => 'editable',
            ), Gender::toText(_profile()->details->gender)
    );?>
    <label><?php echo _t('profile', 'mobile'); ?></label>
    <?php echo CHtml::tag('div', array(
        'id' => 'mobile',
        'class' => 'editable',
            ), _profile()->details->mobile
    ); ?>
    <label><?php echo _t('profile', 'birthday'); ?></label>
    <?php
    echo CHtml::tag('div', array(
        'id' => 'birthdate',
//        'class' => 'editable',
            ), _profile()->details->birthdate ? : _t('profile', 'empty.birthdate')
    );

//    $this->widget('zii.widgets.jui.CJuiDatePicker', array(
//        'id' => 'dob_datepicker',
//        'name' => 'birthdate',
//        'value' => _profile()->details->birthdate,
//        'language' => _app()->language,
//        'options' => array(
//            'dateFormat' => 'yy-mm-dd',
//            'changeMonth' => true,
//            'changeYear' => true,
//            'yearRange' => '-100:+0',
//            'maxDate' => 'today',
//            'onSelect' => 'js:onDatepickerSelect',
//        ),
//        'htmlOptions' => array(
//            'style' => 'visibility: hidden',
//        ),
//    ));

    ?>
    <label><?php echo _t('profile', 'newsletter'); ?></label>
    <?php echo CHtml::tag('div', array(
        'id' => 'newsletter',
        'class' => 'editable',
            ), _profile()->details->newsletter ? _t('profile', 'yes') : _t('profile', 'no')
    ); ?>
    <hr/>
    <h2 style="color: #484743;"><?php echo _t('profile', 'password change'); ?></h2>
    <?php echo _user()->hasFlash('error') ? _user()->getFlash('error') : ''; ?>
    <?php echo CHtml::form(); ?>
    <?php echo CHtml::label(_t('profile', 'new password'), 'pass[new]'); ?>
    <?php echo CHtml::passwordField('pass[new]'); ?>
    <?php echo CHtml::label(_t('profile', 'repeat password'), 'pass[repeat]'); ?>
    <?php echo CHtml::passwordField('pass[repeat]'); ?>
    <?php echo CHtml::submitButton(_t('profile', 'save')); ?>
    <?php echo CHtml::endForm(); ?>
</div>
<script>
    var options = {
//        cssclass: 'inline-edit',
        indicator : '<?php echo CHtml::image(Utils::imageUrl('loading.gif')); ?>',
        submit  : 'OK',
        width: 400,
        autowidth: false,
        placeholder: '<?php echo _t('profile', 'edit text'); ?>',
        maxlength: 45,
        tooltip : '<?php echo _t('profile', 'editable tooltip'); ?>'
    };

    $('#fullname').editable('updateProfile', options);
    $('#gender').editable('updateProfile', {
        indicator : '<?php echo CHtml::image(Utils::imageUrl('loading.gif')); ?>',
        submit  : 'OK',
        type: 'select',
        data: '<?php echo json_encode(Gender::getGenders()); ?>',
        width: 400,
        autowidth: false,
        placeholder: '<?php echo _t('profile', 'edit text'); ?>',
        maxlength: 45,
        tooltip : '<?php echo _t('profile', 'editable tooltip'); ?>'
    });
    $('#newsletter').editable('updateProfile', {
        indicator : '<?php echo CHtml::image(Utils::imageUrl('loading.gif')); ?>',
        submit  : 'OK',
        type: 'checkbox',
        autowidth: false,
        checkbox: { trueValue: '<?php echo _t('profile', 'yes'); ?>', falseValue: '<?php echo _t('profile', 'no'); ?>' },
        tooltip : '<?php echo _t('profile', 'editable tooltip'); ?>'
    });
    $('#mobile').editable('updateProfile', options);
    $('#email').editable('updateProfile', options);
//    $('#birthdate').editable('updateProfile', options);
//    $('#birthdate').click(function(){
//        $('#dob_datepicker').datepicker('show');
//    });

    function onDatepickerSelect(dateText, inst) {
<?php
echo CHtml::ajax(array(
    'url' => array('user/updateProfile'),
    'data' => "js:{id : 'birthdate', value : $('#dob_datepicker').val()}",
    'type' => 'post',
    'update' => '#birthdate',
));
?>
    }
</script>

protected/views/user/_invites.php
<table class="custom-table">
    <thead>
        <tr>
            <th><?php echo _t('profile', 'tableheader.invitee'); ?></th>
            <th><?php echo _t('profile', 'tableheader.invite status'); ?></th>
            <th><?php echo _t('profile', 'tableheader.invited on'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (_profile()->invites as $invite) : ?>
        <tr>
            <td><?php echo $invite->invited_email; ?></td>
            <td><?php echo InviteStatus::toText($invite->status); ?></td>
            <td><?php echo Utils::date($invite->timestamp); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

protected/views/user/_points.php
<h2><?php echo _t('profile', 'total points'); ?>:&nbsp;<span class="total-points"><?php echo _profile()->details->points; ?></span></h2>
<table class="custom-table">
    <thead>
        <tr>
            <th style="text-align: right; width: 10%;"><?php echo _t('profile', 'points'); ?></th>
            <th><?php echo _t('profile', 'reason'); ?></th>
            <th><?php echo _t('profile', 'transaction date'); ?></th>
            <th><?php echo _t('profile', 'points expire'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach (_profile()->pointTransactions as $trans) : ?>
        <tr style="background-color:<?php echo $trans->points > 0 ? '#d3ffd1' : 'pink'; ?>;">
            <td style="text-align: right;"><?php echo $trans->points; ?></td>
            <td><?php echo PointTransactionReason::toText($trans->reason); ?></td>
            <td><?php echo Utils::date($trans->transaction_date); ?></td>
            <td><?php echo Utils::dateLeft($trans->transaction_date, 'P8M'); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

protected/views/user/activation_failed.php
<?php

echo _t('user', 'activation failed. either the code is incorrect or it\'s expired. please contect us at support@dealspot.gr');

protected/views/user/changePassword.php
<div class="white-box">
    <div class="form">

        <?php
        $form = $this->beginWidget('CActiveForm', array(
            'id' => 'user-password-form',
            'enableAjaxValidation' => false,
            'enableClientValidation' => false,
            'focus' => array($user, 'password'),
            'action' => 'submitPassword'
                ));
        ?>

        <div class="row">
            <?php echo $form->labelEx($user, 'password'); ?>
            <?php echo $form->passwordField($user, 'password'); ?>
            <?php echo $form->error($user, 'password'); ?>
        </div>
        <div class="row">
            <?php echo $form->labelEx($user, 'password2'); ?>
            <?php echo $form->passwordField($user, 'password2'); ?>
            <?php echo $form->error($user, 'password2'); ?>
        </div>
        <?php echo $form->hiddenField($user, 'id'); ?>
        <div class="row buttons">
            <?php echo CHtml::submitButton(_t('user', 'send')); ?>
        </div>

        <?php $this->endWidget(); ?>
    </div>
</div>

protected/views/user/coupon.php
<?php $this->renderPartial('//shop/_coupon', array('coupon' => $coupon)); ?>

protected/views/user/forgotPasswordForm.php
<div class="white-box">
    <div class="form">
        <?php echo _user()->hasFlash('error') ? CHtml::tag('span', array('class' => 'errorMessage'), _user()->getFlash('error')) : ''; ?>

        <?php echo CHtml::form('resetCode'); ?>

        <h2><?php echo _t('user', 'enter your email that you used to register.'); ?></h2>
        <div class="info">
            <?php echo _t('user', 'if you registered with your facebook account, provide the email that you use for your facebook account'); ?>
        </div>
        <div style="text-align: center;"><?php echo _t('user', 'you will receive a temporary code in your email'); ?></div>
        <div class="row">
            <?php echo CHtml::label(_t('user', 'your email'), 'email', array('style' => 'font-size: 1.2em;')); ?>
            <?php echo CHtml::textField('email'); ?>
        </div>
        <div class="row buttons">
            <?php echo CHtml::image(Utils::imageUrl('send.png'), '', array('onclick' => '$("form").submit();')); ?>
        </div>
        <p style="text-align: right;">
            <em>
                <?php echo CHtml::link(_t('user', "click here if you've already requested and received a code"), _url('user/resetCode'));
                ?>
            </em>
        </p>
    </div>
</div>

protected/views/user/index.php
<?php foreach ($deals as $deal) : ?>
    <div class="deal">
        <div class="deal-title left"><?php echo $deal->name; ?></div>
        <div class="deal-tag right"><div><strong>- <?php echo $deal->coupon_perc; ?></strong></div></div>
        <div class="clear"></div>
        <div class="deal-description left"><strong><?php echo _t('at') . '&nbsp;' . $deal->company->name; ?></strong></div>
        <div class="deal-price right"><strong><?php echo Utils::currency($deal->coupon_price); ?></strong></div>
        <div class="clear"></div>
        <div class="deal-image"><?php echo CHtml::image(Utils::imageUrl('deals/' . $deal->image)); ?></div>
        <div class="deal-time-wrapper">
            <div class="deal-time-bg"></div>
            <div class="deal-time-wrapper">
                <div class="deal-time">
                    <?php echo CHtml::image(Utils::imageUrl('clock25x25.png'), '', array('class' => 'clock')); ?>
                    <?php echo CHtml::image(Utils::imageUrl('sprite.png'), '', array('class' => 'dots')); ?>
                    <span class="countdown-time"><strong><?php $this->widget('CountDown', array('seconds' => $deal->time_left)); ?></strong></span>
                    <span class="deal-button"><?php echo CHtml::link(_t('Make a deal!'), _url('deal/index', array('id' => $deal->id))); ?></span>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>

protected/views/user/profile.php
<div class="tabscontainer">
    <div class="tabs">
        <div class="tab first <?php echo $selected['details'] ? 'selected' : ''; ?>" id="tab_menu_1">
            <div class="link"><?php echo _t('profile', 'profile'); ?></div>
        </div>
        <div class="tab <?php echo $selected['deals'] ? 'selected' : ''; ?>" id="tab_menu_2">
            <div class="link"><?php echo _t('profile', 'deals'); ?></div>
        </div>
        <div class="tab <?php echo $selected['invites'] ? 'selected' : ''; ?>" id="tab_menu_3">
            <div class="link"><?php echo _t('profile', 'invites'); ?></div>
        </div>
        <div class="tab last <?php echo $selected['points'] ? 'selected' : ''; ?>" id="tab_menu_4">
            <div class="link"><?php echo _t('profile', 'points'); ?></div>
        </div>
        <?php if (User::hasRole(Role::CLIENT)) : ?>
            <div class="tab last <?php echo $selected['company'] ? 'selected' : ''; ?>" id="tab_menu_5">
                <div class="link"><?php echo _t('profile', 'company'); ?></div>
            </div>
        <?php endif; ?>
    </div>
    <div class="curvedContainer">
        <div class="tabcontent <?php echo $selected['details']; ?>" id="tab_content_1"><?php echo $details; ?></div>
        <div class="tabcontent <?php echo $selected['deals']; ?>" id="tab_content_2"><?php echo $deals; ?></div>
        <div class="tabcontent <?php echo $selected['invites']; ?>" id="tab_content_3"><?php echo $invites; ?></div>
        <div class="tabcontent <?php echo $selected['points']; ?>" id="tab_content_4"><?php echo $points; ?></div>
        <?php if (User::hasRole(Role::CLIENT)) : ?>
            <div class="tabcontent <?php echo $selected['company']; ?>" id="tab_content_5"><?php echo $company; ?></div>
        <?php endif; ?>
    </div>
</div>
<script>
    $(document).ready(function() {
 
        $(".tabs .tab[id^=tab_menu]").click(function() {
            var curMenu=$(this);
            
            $(".tabs .tab[id^=tab_menu]").removeClass("selected");
            curMenu.addClass("selected");
 
            var index=curMenu.attr("id").split("tab_menu_")[1];
            
            $(".curvedContainer .tabcontent").removeClass("show");
            
            $(".curvedContainer #tab_content_"+index).html('<div class="loader"><?php echo CHtml::image(Utils::imageUrl('loading.gif')); ?></div>');
            $(".curvedContainer #tab_content_"+index).addClass("show");
            
            switch (index) {
                case '1':
                    var url = '<?php echo _url('user/details'); ?>';
                    break;
                case '2':
                    var url = '<?php echo _url('user/deals'); ?>';
                    break;
                case '3':
                    var url = '<?php echo _url('user/invites'); ?>';
                    break;
                case '4':
                    var url = '<?php echo _url('user/points'); ?>';
                    break;
                case '5':
                    var url = '<?php echo _url('user/company'); ?>';
                    break;
                }
            
                $.ajax({
                    url: url,
                    cache: false,
                    success: function(response) {
                        $(".curvedContainer #tab_content_"+index).html(response);
                    }
                })
            });
        });
</script>